from dotenv import load_dotenv
import os

load_dotenv()

GOOGLE_API_KEY=os.getenv('GOOGLE_API_KEY')
MONGODB_CONNECTION_STRING=os.getenv("MONGODB_CONNECTION_STRING")
AZURE_OPENAI_ENDPOINT=os.getenv('AZURE_OPENAI_ENDPOINT')
AZURE_OPENAI_API_KEY=os.getenv('AZURE_OPENAI_API_KEY')
GROQ_API_KEY=os.getenv('GROQ_API_KEY')
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_ENDPOINT = os.getenv("QDRANT_ENDPOINT")


