from dotenv import load_dotenv
import os

load_dotenv()

GOOGLE_API_KEY=os.getenv('GOOGLE_API_KEY')
MONGODB_CONNECTION_STRING=os.getenv("MONGODB_CONNECTION_STRING")
AZURE_OPENAI_ENDPOINT=os.getenv('AZURE_OPENAI_ENDPOINT')
AZURE_OPENAI_API_KEY=os.getenv('AZURE_OPENAI_API_KEY')